with RECURSIVE ECOLI_GRAPH AS(

    SELECT e.ID, e.PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA e
    WHERE ISNULL(e.PARENT_ID)
    
    UNION ALL
    
    SELECT e1.ID, e1.PARENT_ID, e2.GEN+1 AS GEN
    FROM ECOLI_DATA e1
    INNER JOIN ECOLI_GRAPH e2
    ON e1.PARENT_ID = e2.ID
)

SELECT ID
FROM ECOLI_GRAPH EG
WHERE EG.GEN=3
ORDER BY ID;