SELECT D.ID, IFNULL(C.CNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA D 
LEFT JOIN (
    SELECT E1.ID, COUNT(E1.ID) AS CNT
    FROM ECOLI_DATA E1 LEFT JOIN ECOLI_DATA E2 ON E1.ID = E2.PARENT_ID
    WHERE E2.ID IS NOT NULL
    GROUP BY E1.ID) C
ON D.ID=C.ID
ORDER BY D.ID