SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM (
    SELECT USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
    FROM ONLINE_SALE
    WHERE SALES_DATE BETWEEN '2022-03-01'AND '2022-03-31'
) ONL UNION ALL(
    SELECT SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT 
    FROM OFFLINE_SALE
    WHERE SALES_DATE BETWEEN '2022-03-01'AND '2022-03-31'
)
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;