SELECT C.CAR_ID, C.CAR_TYPE, FLOOR(C.DAILY_FEE * ((100 - P.DISCOUNT_RATE) * 0.01)) * 30 AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR C
INNER JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON 
    P.CAR_TYPE = C.CAR_TYPE
LEFT JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON 
    C.CAR_ID = H.CAR_ID 
    AND (MONTH(H.START_DATE) = 11 OR MONTH(H.END_DATE) = 11 OR (H.START_DATE <= '2022-11-01' AND H.END_DATE >= '2022-11-30'))
WHERE 
    (C.CAR_TYPE LIKE '세단' OR C.CAR_TYPE LIKE 'SUV')
    AND P.DURATION_TYPE LIKE '30일 이상'
    AND H.CAR_ID IS NULL
    AND (C.DAILY_FEE * ((100 - P.DISCOUNT_RATE) * 0.01)) * 30 BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;