WITH TOTAL_COUNT AS (
    SELECT COUNT(*) AS CNT FROM ECOLI_DATA
)
SELECT E.ID,
    CASE
        WHEN (R.RNK)<=TC.CNT*0.25 THEN 'CRITICAL'
        WHEN (R.RNK)<=TC.CNT*0.5 THEN 'HIGH'
        WHEN (R.RNK)<=TC.CNT*0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM ECOLI_DATA E
    LEFT JOIN (
        SELECT ID, RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS RNK FROM ECOLI_DATA
        ) R
    ON E.ID=R.ID
    CROSS JOIN TOTAL_COUNT TC
ORDER BY E.ID;