SELECT ID,
    CASE
        WHEN RNK=1 THEN 'CRITICAL'
        WHEN RNK=2 THEN 'HIGH'
        WHEN RNK=3 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (SELECT ID, NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) AS RNK FROM ECOLI_DATA) D 
ORDER BY ID;