SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, R.AVG AS SCORE
FROM (SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS
    FROM REST_INFO
    WHERE ADDRESS LIKE '서울%') I 
INNER JOIN ( SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS AVG
    FROM REST_REVIEW
    GROUP BY REST_ID
) R 
ON R.REST_ID = I.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;