SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) MONTH, COUNT(DISTINCT O.USER_ID) PURCHASED_USERS, 
    ROUND(COUNT(DISTINCT O.USER_ID)/(SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021) , 1) AS PUCHASED_RATIO
FROM ONLINE_SALE O INNER JOIN(
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
) U ON O.USER_ID = U.USER_ID
GROUP BY  YEAR(O.SALES_DATE),MONTH(O.SALES_DATE)
ORDER BY  YEAR(O.SALES_DATE),MONTH(O.SALES_DATE);