SELECT 
    YEAR(SALES_DATE) YEAR,  
    MONTH(SALES_DATE) MONTH, 
    count(distinct O.user_id ) PURCHASED_USERS,  
    ROUND(count(distinct O.user_id )/(select count(*) from USER_INFO where YEAR(JOINED)=2021), 1) PUCHASED_RATIO
FROM 
    ONLINE_SALE O
INNER JOIN USER_INFO U
ON O.USER_ID=U.USER_ID AND YEAR(U.JOINED)=2021
GROUP BY YEAR , MONTH
ORDER BY YEAR , MONTH;