-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT A
INNER JOIN PATIENT P ON P.PT_NO = A.PT_NO
INNER JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
WHERE APNT_CNCL_YN = "N" AND A.MCDP_CD = "CS" AND YEAR(APNT_YMD)=2022 AND MONTH(APNT_YMD)=4 AND DAY(APNT_YMD)=13
ORDER BY APNT_YMD;