SELECT USER_ID,NICKNAME, TOTAL_SALES
from USED_GOODS_USER U INNER JOIN (
    select SUM(PRICE) AS TOTAL_SALES, WRITER_ID
    from USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
) P ON U.USER_ID = P.WRITER_ID
WHERE TOTAL_SALES>=700000
order by TOTAL_SALES;

