SELECT M.MEMBER_NAME, REV.REVIEW_TEXT, DATE_FORMAT(REV.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE M INNER JOIN (
    SELECT R.MEMBER_ID, R.REVIEW_TEXT, R.REVIEW_DATE
    FROM REST_REVIEW R INNER JOIN(
            SELECT MEMBER_ID ,COUNT(*) CNT
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
            ORDER BY CNT DESC
            LIMIT 1) C
    ON R.MEMBER_ID = C.MEMBER_ID
    ) REV ON REV.MEMBER_ID = M.MEMBER_ID
ORDER BY REV.REVIEW_DATE, REV.REVIEW_TEXT;
