SELECT DISTINCT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") as REVIEW_DATE
FROM REST_REVIEW R 
    INNER JOIN MEMBER_PROFILE M 
        ON R.MEMBER_ID = M.MEMBER_ID
    INNER JOIN (SELECT MEMBER_ID, count(MEMBER_ID) as MEMBER_COUNT
                FROM REST_REVIEW
                GROUP BY MEMBER_ID
               )C 
        ON C.MEMBER_ID = R.MEMBER_ID
    INNER JOIN (SELECT COUNT(MEMBER_ID) AS MAX
                FROM REST_REVIEW
                GROUP BY MEMBER_ID
                ORDER BY COUNT(MEMBER_ID) DESC
                LIMIT 1)CM
        ON CM.MAX = C.MEMBER_COUNT
ORDER BY M.MEMBER_ID, REVIEW_DATE, REVIEW_TEXT