SELECT ID, FISH_NAME, LENGTH
FROM FISH_NAME_INFO I INNER JOIN (
    SELECT  ID, FISH_TYPE, LENGTH, RANK() OVER(PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) RNK
    FROM FISH_INFO
) N ON I.FISH_TYPE = N.FISH_TYPE
WHERE N.RNK=1
ORDER BY ID;