SELECT D.DEPT_ID, D.DEPT_NAME_EN, ROUND(H.AVG, 0) AS AVG_SAL
FROM HR_DEPARTMENT D INNER JOIN
    (SELECT DEPT_ID, SUM(SAL)/COUNT(*) AS AVG
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID) H
    ON D.DEPT_ID = H.DEPT_ID
ORDER BY H.AVG DESC
