SELECT B.CATEGORY, SUM(sales) as TOTAL_SALES
FROM 
    BOOK_SALES S
join
    BOOK B
on 
    S.BOOK_ID=B.BOOK_ID
WHERE YEAR(S.SALES_DATE)=2022 and MONTH(S.SALES_DATE)=1
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY