SELECT F.CATEGORY, MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F INNER JOIN (
SELECT DISTINCT CATEGORY, MAX(PRICE) OVER (PARTITION BY CATEGORY ) AS MAX_PRICE
FROM FOOD_PRODUCT
ORDER BY MAX_PRICE DESC) P ON F.CATEGORY = P.CATEGORY
WHERE F.CATEGORY IN ('과자','국','김치','식용유') AND F.PRICE = P.MAX_PRICE
ORDER BY MAX_PRICE DESC